#!/usr/bin/bash
# Getting input
[ -z "$1" ] && opt=-h || opt=$1

############################################################
# R packages
############################################################
if [ $opt = -r ] || [ $opt = --rPackages ]; then
	# Basic packages
	echo "r-base & r-essentials"
	conda install -c r r-base r-essentials -y
	echo "varhandle & config"
	conda install -c conda-forge r-varhandle r-config -y

	# Seurat
	echo "seurat"
	conda install -c conda-forge r-seurat=3.2.3 -y

	# soupx
	echo "soupx"
	conda install -c conda-forge r-soupx -y

	# decontx via celda & biocmanager
	echo "biocmanager"
	conda install -c conda-forge r-biocmanager -y
	echo "celda"
	Rscript -e 'BiocManager::install("celda")'

	# packages required for analysis
	echo "ggplot2, xlsx, reshape2"
	conda install -c r r-ggplot2 r-xlsx r-reshape2 -y
	echo "plotly, cowplot, patchwork"
	conda install -c conda-forge r-plotly r-cowplot r-patchwork -y
	echo "orca"
	conda install -c plotly plotly-orca -y

	# others
	conda install -c conda-forge r-htmlwidgets r-vctrs -y
############################################################
# CellBender (CPU)
############################################################
elif [ $opt = -c ] || [ $opt = --cellbenderCPU ]; then
	echo "WIP"

############################################################
# CellBender (GPU)
############################################################
elif [ $opt = -g ] || [ $opt = --cellbenderGPU ]; then
	echo "WIP"

############################################################
# Options
############################################################
else
	echo "Options:"
	echo "  -r || --rPackages     > install R packages in current conda environment"
	echo "  -c || --cellbenderCPU > install cellbender (CPU version) in the current conda environment"
	echo "  -g || --cellbenderGPU > install cellbender (GPU version) in the current conda environment"
fi
