default:
	input_dir: ""
	output_dir: ""
	# ARRAY available options = ["decontaminate" "integrate" "analyse"
	process: ""
	# ARRAY available options = ["no_decontamination" "soupx:autoEstCont" "soupx:background_genes" "soupx:top_background_genes" 
	#							  "decontX:no_cell_types" "decontX:with_cell_types" "cellbender"]
	method: ""
	dataset: ""
	# optional params
	recluster: False
	original_cell_annotations_file: "" #only used for comparison for reclustering w/ no decont
	new_cell_annotations_file: "" #used for clusters for new decont
	alpha: 0.05
	threads: 1
	# list of genes separated by `|`
	genes_>=9_cts: "Gpx3|Hbb-bs|Hbb-bt|Hba-a2|AY036118|Fxyd2|Gpx1|Hba-a1|Spink1"
	ct_order_dotplots: "PT|Endo|CD_IC|MC|B|DCT_CNT|CNT|DCT|NK|T|CD_PC|Unknown|aLOH|Podo|MPH|Fib"
	pie_plot_cts: "PT|Endo|MPH|CD_IC|DCT_CNT"

harry:
	input_dir: ""
	output_dir: ""
	process:
		- "decontaminate"
		- "integrate"
		- "analysis"
	method:
		- "no_decontamination"
		- "soupx:autoEstCont"
	dataset: "mouse_kidney"
