default:
  input_dir: ""
  output_dir: ""
  # ARRAY available options = ["decontaminate" "integrate" "analyse"
  process: ""
  # ARRAY available options = ["no_decontamination" "soupx:autoEstCont" "soupx:background_genes" "soupx:top_background_genes" 
  #                            "decontX:no_cell_types" "decontX:with_cell_types" "cellbender"]
  methods: ""
  dataset: "" # mouse_kidney || hgmm12k
  sample_ids: "BG1_BG20C|BG3_BG21C|BG5_BG22C|BG52_BG20C_MeOH|BG54_BG21C_MeOH|BG56_BG22C_MeOH" # sample_ids for mouse_kidney || hg19|mm10
  # optional params
  original_cell_annotations: "" #only used for comparison for reclustering w/ no decont
  new_cell_annotations: "" #used for decontamination and comparison
  gene_signatures: ""
  recluster: False
  quiet: False
  alpha: 0.05
  threads: 1
  # list of genes separated by `|`
  genes_ct_dotplots: "Gpx3|Hbb-bs|Hbb-bt|Hba-a2|AY036118|Fxyd2|Gpx1|Hba-a1|Spink1"
  ct_order_dotplots: "PT|Endo|CD_IC|MC|B|DCT_CNT|CNT|DCT|NK|T|CD_PC|aLOH|Podo|MPH|Fib"
  pie_plot_cts: "PT|Endo|MPH|CD_IC|DCT_CNT|CNT"
  summary_histogram_labels: # labels for the summary histogram - must be in same order as methods
    - "No Decont-amination"
    - "SoupX: Using autoEstCont"
    - "SoupX: 3 Markers per Cell Type"
    - "SoupX: Top 25 Marker Genes"
    - "DecontX: No Cell Types"
    - "DecontX: With Cell Types"
    - "CellBender"

harry:
  input_dir: "/home/harry/Perkins/Human_Mouse/data"
  output_dir: "/home/harry/Perkins/Human_Mouse/results"
  process:
  - "decontaminate"
  methods: 
  - "no_decontamination"
  dataset: "hgmm12k"
  sample_ids: "hg19|mm10"
  original_cell_annotations: "gem_classification.csv"
  # new_cell_annotations: "../new_results/reclus/no_decontamination/new_clus.tsv"
  # gene_signatures: "cell_type_gene_signatures.xlsx"
  # ocra_dir: "../../new_results/reclus"
  recluster: False

pawsey:
  input_dir: "/data/harry_decont_project/hgmm12k/data"
  output_dir: "/data/harry_decont_project/hgmm12k/results/first_attempt"
  process:
  - "decontaminate"
  methods: 
  - "decontx:no_cell_types"
  dataset: "hgmm12k"
  sample_ids: "hg19|mm10"
  original_cell_annotations: "gem_classification.csv"
  recluster: False

pawsey2:
  input_dir: "/data/harry_decont_project/hgmm12k/data"
  output_dir: "/data/harry_decont_project/hgmm12k/results/first_attempt"
  process:
  - "decontaminate"
  methods: 
  - "soupx:autoEstCont"
  dataset: "hgmm12k"
  sample_ids: "hg19|mm10"
  original_cell_annotations: "gem_classification.csv"
  recluster: False

pawsey_reclus:
  input_dir: "/data/harry_decontx/decont_project/mouse_kidney/input"
  output_dir: "/data/harry_decontx/decont_project/mouse_kidney/output_reclus"
  process:
    - "decontaminate"
  methods: 
  - "soupx:autoEstCont"
  - "soupx:background_genes"
  - "soupx:top_background_genes"
  - "decontx:no_cell_types"
  - "decontx:with_cell_types"
  - "cellbender"
  dataset: "mouse_kidney"
  original_cell_annotations: "cell_annotations.xlsx"
  new_cell_annotations: "../mouse_kidney/output_reclus/no_decontamination/new_clus.tsv"
  gene_signatures: "gene_signatures.xlsx"
  recluster: True
  threads: 4

benchmarking:
  input_dir: "/home/harry/perkins/benchmarking/input"
  output_dir: "/home/harry/perkins/benchmarking/output"
  process: "decontaminate"
  methods: "null"
  dataset: "mouse_kidney"
  original_cell_annotations: "cell_annotations.xlsx"
  gene_signatures: "gene_signatures.xlsx"
