#!/usr/bin/bash
output=$1
methods=("no_decontamination" "soupx:autoEstCont" "soupx:background_genes" "soupx:top_background_genes" "decontx:no_cell_types" "decontx:with_cell_types" "cellbender")

for i in ${methods[@]}; do
	mkdir -p $1/$i/matrices
	mkdir -p $1/$i/Rda/decontaminated_samples
	mkdir $1/$i/plots
done
